
cat ./fastq/pass/barcode01/*.fastq > barcode01.fastq
cat ./fastq/pass/barcode02/*.fastq > barcode02.fastq
cat ./fastq/pass/barcode03/*.fastq > barcode03.fastq
cat ./fastq/pass/barcode04/*.fastq > barcode04.fastq
cat ./fastq/pass/barcode05/*.fastq > barcode05.fastq
cat ./fastq/pass/barcode06/*.fastq > barcode06.fastq
cat ./fastq/pass/barcode07/*.fastq > barcode07.fastq
cat ./fastq/pass/barcode08/*.fastq > barcode08.fastq
cat ./fastq/pass/barcode09/*.fastq > barcode09.fastq
cat ./fastq/pass/barcode10/*.fastq > barcode10.fastq
cat ./fastq/pass/barcode11/*.fastq > barcode11.fastq
cat ./fastq/pass/barcode12/*.fastq > barcode12.fastq
cat ./fastq/pass/barcode13/*.fastq > barcode13.fastq
cat ./fastq/pass/barcode14/*.fastq > barcode14.fastq
cat ./fastq/pass/barcode15/*.fastq > barcode15.fastq
cat ./fastq/pass/barcode16/*.fastq > barcode16.fastq
cat ./fastq/pass/barcode17/*.fastq > barcode17.fastq
cat ./fastq/pass/barcode18/*.fastq > barcode18.fastq
cat ./fastq/pass/barcode19/*.fastq > barcode19.fastq
